modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"

[[mods]]
modId = "hqsimplef3"
version = "1.0.0"
displayName = "HQSimpleF3"
authors = "Cosine_A"
description = "F3을 간략하게 보여줍니다."